trip/app1/urls.py
from django.urls import path
from . import views 

app_name = 'app1'

urlpatterns = [
    path('', views.registration, name='registration'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('new-trip', views.new_trip, name='new_trip'),
    path('add', views.add, name='add'),
    path('view_trip/<int:pk>', views.view_trip, name='view_trip'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('details/<int:pk>', views.details, name='details'),
    path('my-trips', views.my_trips, name='my_trips'),
    path('join/<int:pk>', views.join, name='join'),
    path('cancel/<int:pk>', views.cancel, name='cancel')

]

trip/trip/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
]

trip/app1/models.py
from django.db import models

# Create your models here.


class UsersManger(models.Manager):
    def validate(self, post_data):
        errors = {}
        if len(post_data['first_name']) < 2:
            errors['first_name'] = 'First name should be at least 2 charters'
        if len(post_data['last_name']) < 2:
            errors['last_name'] = 'Last name should be at least 2 charters'    
        if len(post_data['password1']) < 8:
            errors['password1'] = 'Password should be at least 8 charters'
            
        return errors


class User(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=50)
    
    
    objects = UsersManger()
    
    


class TripManger(models.Manager):
    def validate(self, post_data):
        errors = {}
        if len(post_data['destination']) < 2:
            errors['destination'] = 'destination should be at least 2 charters'
        if len(post_data['Itinerary']) > 50:
            errors['Itinerary'] = 'Itinerary should be less than 50 charters'    
        return errors

class Trip(models.Model):
    destination = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    Itinerary = models.TextField()
    organizer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    travelers = models.ManyToManyField(User, related_name='travelers')
    
    objects = TripManger()

trip/app1/views.py
from django.shortcuts import render, redirect
from .models import User, Trip
from django.contrib import messages
import bcrypt


def registration(request):
    user_id = request.session.get("user_id")

    if user_id:
        return redirect("app1:dashboard")

    return render(request, "registration.html")


def register(request):
    if request.method == "POST":

        errors = User.objects.validate(request.POST)

        # There is some errors
        if len(errors) > 0:
            for error in errors.values():
                messages.error(request, error)
            return redirect("app1:registration")

        # بنستخرج المدخلات من الفورم
        first_name_form = request.POST["first_name"]
        last_name_form = request.POST["last_name"]
        email_form = request.POST["email"]
        password_form = request.POST["password1"]
        confirm_password_form = request.POST["password2"]

        if password_form == confirm_password_form:
            hash_password = bcrypt.hashpw(
                password_form.encode(), bcrypt.gensalt()
            ).decode()

            new_user = User.objects.create(
                first_name=first_name_form,
                last_name=last_name_form,
                email=email_form,
                password=hash_password,
            )

            request.session["user_id"] = new_user.id
            request.session["first_name"] = new_user.first_name

            return redirect("app1:dashboard")

        # if password didn't match
        else:
            messages.error(request, "Password not match.")
            return redirect("app1:registration")


def login(request):
    if request.method == "POST":
        email_form = request.POST["email"]
        password_form = request.POST["password1"]

        users = User.objects.filter(email=email_form)

        if len(users) == 0:
            messages.error(request, "Email doesn't exist.")
            return redirect("app1:registration")

        if bcrypt.checkpw(password_form.encode(), users.first().password.encode()):
            request.session["user_id"] = users[0].id
            request.session["first_name"] = users[0].first_name

            return redirect("app1:dashboard")
        # if password is wrong
        else:
            messages.error(request, "Password not correct.")
            return redirect("app1:registration")


def logout(request):
    request.session.flush()
    return redirect("app1:registration")


def dashboard(request):
    all_trips = Trip.objects.all()
    user = User.objects.get(id=request.session["user_id"])

    context = {"trips": all_trips, "current_user": user}
    return render(request, "dashboard.html", context)


def new_trip(request):
    return render(request, "newtrip.html")


def add(request):
    destination_form = request.POST["destination"]
    start_date_form = request.POST["start_date"]
    end_date_form = request.POST["end_date"]
    Itinerary_form = request.POST["Itinerary"]

    errors = Trip.objects.validate(request.POST)

    # There is some errors
    if len(errors) > 0:
        for error in errors.values():
            messages.error(request, error)
        return redirect("app1:new_trip")

    user = User.objects.get(id=request.session["user_id"])

    Trip.objects.create(
        start_date=start_date_form,
        end_date=end_date_form,
        destination=destination_form,
        Itinerary=Itinerary_form,
        organizer=user,
    )

    return redirect("app1:dashboard")


def view_trip(request, pk):
    trip = Trip.objects.get(pk=pk)
    context = {
        "trip": trip,
    }
    return render(request, "if_organized_by.html", context)


def edit(request, pk):
    destination_form = request.POST["destination"]
    start_date_form = request.POST["start_date"]
    end_date_form = request.POST["end_date"]
    Itinerary_form = request.POST["Itinerary"]

    trip = Trip.objects.get(pk=pk)

    trip.start_date = start_date_form
    trip.end_date = end_date_form
    trip.Itinerary = Itinerary_form
    trip.destination = destination_form

    trip.save()

    return redirect("app1:dashboard")


def delete(request, pk):
    trip = Trip.objects.get(pk=pk)
    trip.delete()
    return redirect("app1:dashboard")



def details(request, pk):
    trip = Trip.objects.get(pk=pk)
    context = {
        'trip': trip
    }
    return render(request, "if_not_organized_by.html", context)


def my_trips(request):
    user = User.objects.get(id=request.session["user_id"])
    
    my_trips = Trip.objects.filter(travelers=user)
    other_trips = Trip.objects.all().exclude(travelers=user)
    
    context = {
        'my_trips': my_trips,
        'other_trips': other_trips
    }
    
    return render(request, "mytrip.html", context)



def join(request, pk):
    user = User.objects.get(id=request.session["user_id"])
    trip = Trip.objects.get(id=pk)
    
    trip.travelers.add(user)
    
    return redirect("app1:my_trips")


def cancel(request, pk):
    user = User.objects.get(id=request.session["user_id"])
    trip = Trip.objects.get(id=pk)
    
    trip.travelers.remove(user)
    
    return redirect("app1:my_trips")

trip/app1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />

</head>

<body>

  <div class="container text-left mt-6">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'app1:dashboard'%}">Hello ,
                {{request.session.first_name}} !</a>
            </li>
          </ul>
          <ul style="list-style: none;" class="ms-auto d-flex gap-3 m-0">


            <li class="nav-item ">
              <a style="text-decoration: underline;" class=" nav-link active text-primary" aria-current="page"
                href="{% url 'app1:dashboard' %}">Dashboard</a>
            </li>

          </ul>

          <ul style="list-style: none;" class="ms-auto d-flex gap-3 m-0">


            <li class="nav-item ">
              <a style="text-decoration: underline;" class=" nav-link active text-primary" aria-current="page"
                href="{% url 'app1:logout' %}">Log out</a>
            </li>

          </ul>

        </div>
      </div>
    </nav>

    <div class="container">
      {% block content %}

      {% endblock content %}
    </div>



  </div>
  <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
</body>

</html>

trip/app1/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>dashboard </title>
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
  <link rel="stylesheet" href="../static/tripstyle.css">

</head>

<body>

  <div class="container text-left mt-6">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'app1:dashboard'%}">Hello ,
                {{request.session.first_name}} !</a>
            </li>
          </ul>
          <ul style="list-style: none;" class="ms-auto d-flex gap-3 m-0">


            <li class="nav-item ">
              <a style="text-decoration: underline;" class=" nav-link active text-primary" aria-current="page"
                href="{% url 'app1:logout' %}">Log out</a>
            </li>

          </ul>

        </div>
      </div>
    </nav>


    <br>
    <!-- body contact -->
    <h1>All Trips:</h1>

    <div class="container text-center mt-5">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>destination</th>
            <th>start date </th>
            <th>end date </th>
            <th> organizer </th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for trip in trips %}
          <tr>
            <td>{{trip.destination}}</td>
            <td>{{trip.start_date}}</td>
            <td>{{trip.end_date}}</td>
            <td>{{trip.organizer.first_name}}</td>
            {% if trip.organizer == current_user %}
            <td><a href="{% url 'app1:view_trip' pk=trip.id %}">Edit</a></td>
            {% else %}
            <td><a href="{% url 'app1:details' pk=trip.id %}">Details</a></td>
            {% endif %}
          </tr>
          {% endfor %}
      </table>
    </div>







  </div>

  </div>
  </div>







  <br>
  <br>
  <ul style="list-style: none;" class="ms-auto d-flex gap-3 m-0">


    <li class="nav-item ">
      <a style="text-decoration: underline;" class=" nav-link active text-primary" aria-current="page"
        href="{% url 'app1:new_trip' %}">+ plan a new trip </a>
    </li>

  </ul>






  </div>
  <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
</body>

</html>

trip/app1/templates/if_not_organized_by.html
{% extends './base.html' %}
{% block content %}
<title>Details</title>


<div class="container text-left mt-6">

    <div class="row mt-5" >
        <div class=" col-lg-6" style="border: 2px solid black; max-width: 40%;">
            <div>

                <p>organized_by: {{trip.organizer.first_name}}</p>
                <p>created on: {{trip.created_at}}</p>
                <p>Last updated : {{trip.updated_at}}</p>
                <p>end date: {{ trip.end_date }} </p>
                <p>Itinerary: {{trip.Itinerary}} </p>

            </div>
        </div>


        <div class=" col-lg-6" style="border: 2px solid black; max-width: 40%; margin-left: 100px;">
            <div class="pairent">
                <h1 class="h3">Travelers on this trip :</h1>

                {% for user in trip.travelers.all %}
                <p>{{user.first_name}}</p>
                {% endfor %}

                <a class="my_trip" style="text-decoration: underline;" href="{% url 'app1:my_trips' %}">Go to
                    my trip </a>

            </div>
        </div>

    </div>

</div>













{% endblock content %}

trip/app1/templates/if_organized_by.html
{% extends './base.html' %}
{% block content %}
<title>Edit </title>

<p>Edit trip </p>
<form class="add_Form" action="{% url 'app1:edit' pk=trip.pk %}" method="POST">
  {% csrf_token %}
  <!-- destination Input > type :"text" -->
  <div class="d-flex align-items-center gap-2 mb-3">
    <label for="title" class="col-sm-2 col-form-label">Destination : </label>
    <div style="flex: 1.4" class="col-sm-4">
      <input required type="text" name="destination" class="form-control w-50" id="destination"
        value="{{ trip.destination }}">
    </div>
  </div>
  <!-- start_date  Input > type :"date" -->
  <div class="d-flex align-items-center gap-2 mb-3">
    <label for="title" class="col-sm-2 col-form-label">start_date : </label>
    <div style="flex: 1.4" class="col-sm-4">
      <input required type="date" name="start_date" class="form-control w-50" id="start_date"
        value="{{ trip.start_date|date:'Y-m-d' }}">
    </div>
  </div>
  <!-- end_date  Input > type :"date" -->
  <div class="d-flex align-items-center gap-2 mb-3">
    <label for="title" class="col-sm-2 col-form-label">end_date : </label>
    <div style="flex: 1.4" class="col-sm-4">
      <input required type="date" name="end_date" class="form-control w-50" id="end_date"
        value="{{ trip.end_date|date:'Y-m-d' }}">
    </div>
  </div>

  <!-- start_date Input > type :"textarea" -->
  <div class="form-group d-flex">
    <label for="exampleFormControlTextarea1" class="me-2">Itinerary : </label>
    <textarea class="form-control w-50 " name="Itinerary" id="exampleFormControlTextarea1"
      rows="3">{{ trip.Itinerary }}</textarea>
  </div>
  <div class="submit-btn d-flex justify-content-center ">

    <div class="btn_div d-flex justify-content-center">
      <button style="width: fit-content;
        box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
        , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
        border: 2px solid black;" type="submit" class="btn btn-outline-dark btn-shadow mt-3">
        Update
      </button>

      <a href="{% url 'app1:delete' pk=trip.id %}" class="btn btn-outline-dark btn-shadow mt-3 text-light bg-danger"
        style="text-decoration: none; width: fit-content; box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1), 0 2px 10px 0 rgba(0, 0, 0, 0.12); border: 2px solid black;">
        Delete this trip
      </a>




</form>
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</div>
</div>








{% endblock content %}

trip/app1/templates/mytrip.html
{% extends './base.html' %}
{% block content %}
<title>My trips </title>


<div class="container text-center mt-5">
    <p> MY trip</p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>destination</th>
                <th>start date </th>
                <th>end date </th>
                <th> organizer </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for trip in my_trips %}
            <tr>
                <td>{{trip.destination}}</td>
                <td>{{trip.start_date}}</td>
                <td>{{trip.end_date}}</td>
                <td>{{trip.organizer.first_name}}</td>
                <td><a href="{% url 'app1:cancel' pk=trip.id %}">Cancel</a></td>
            </tr>

        {% endfor %}
    </table>
</div>

<br>
<br>
<br>

<p>other trip you can join </p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>destination</th>
            <th>start date </th>
            <th>end date </th>
            <th> organizer </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for trip in other_trips %}
        <tr>
            <td>{{trip.destination}}</td>
            <td>{{trip.start_date}}</td>
            <td>{{trip.end_date}}</td>
            <td>{{trip.organizer.first_name}}</td>
            <td><a href="{% url 'app1:join' pk=trip.id %}">Join</a></td>
        </tr>

    {% endfor %}
</table>
</div>













{% endblock content %}

trip/app1/templates/newtrip.html
{% extends './base.html' %}
{% block content %}
<title>New </title>

<div class="container text-left mt-6">

  <div class="row mt-5">
    <div class=" col-lg-6">

      <h2>Plan A New Trip</h2>

      <form class="add_Form" action="{% url 'app1:add' %}" method="POST">
        {% csrf_token %}
        <!-- destination Input > type :"text" -->
        <div class="d-flex align-items-center gap-2 mb-3">
          <label for="title" class="col-sm-2 col-form-label">Destination: </label>
          <div style="flex: 1.4" class="col-sm-4">
            <input required type="text" name="destination" class="form-control w-50" id="destination">
          </div>
        </div>
        <!-- start_date  Input > type :"date" -->
        <div class="d-flex align-items-center gap-2 mb-3">
          <label for="title" class="col-sm-2 col-form-label">start_date: </label>
          <div style="flex: 1.4" class="col-sm-4">
            <input required type="date" name="start_date" class="form-control w-50" id="start_date ">
          </div>
        </div>
        <!-- end_date  Input > type :"date" -->
        <div class="d-flex align-items-center gap-2 mb-3">
          <label for="title" class="col-sm-2 col-form-label">end_date: </label>
          <div style="flex: 1.4" class="col-sm-4">
            <input required type="date" name="end_date" class="form-control w-50" id="end_date ">
          </div>
        </div>

        <!-- start_date Input > type :"textarea" -->
        <div class="form-group d-flex">
          <label for="exampleFormControlTextarea1" class="me-2">Itinerary: </label>
          <textarea class="form-control w-50 " name="Itinerary" id="Itinerary" rows="3"></textarea>

        </div>
        <div class="submit-btn d-flex justify-content-center ">

          <button style="width: fit-content;
            box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
            , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
            border: 2px solid black;" type="submit" class="btn btn-outline-dark btn-shadow mt-3"> submit</button>


      </form>
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}
    </div>
  </div>
</div>
</div>


{% endblock content %}

trip/app1/templates/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Login & Registration</title>
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
</head>

<body>

  <div class="container text-left mt-6">
    <div style="display: flex; align-items:center; width: 100%; justify-content:space-between; flex-direction: column;" class="hello">
      <p>Hello World</p>
      <p>Travel planing made easy</p>
    </div>




    <div class="row mt-5">
      <div class="col-lg-6">
        <h1>Registration</h1>
        <br>
        <form action="{% url 'app1:register' %}" method="POST" class="d-flex flex-column gap-3 ">
          {% csrf_token %}
          <!-- Name Input > type :"text" -->
          <div class="d-flex align-items-center gap-2">
            <label for="first_name" class="col-sm-2 col-form-label"> First name : </label>
            <div style="flex: 1.4" class="col-sm-4">
              <input required type="text" name="first_name" class="form-control" id="first_name">
            </div>
          </div>
          <!-- Name Input > type :"text" -->
          <div class="d-flex align-items-center gap-2">
            <label for="last_name" class="col-sm-2 col-form-label"> Last name : </label>
            <div style="flex: 1.4" class="col-sm-4">
              <input required type="text" name="last_name" class="form-control" id="last_name">
            </div>
          </div>
          <!-- email Input > type :type="email" -->
          <div class="d-flex align-items-center gap-2">
            <label for="inputEmail3" class="col-sm-2 col-form-label"> Email : </label>
            <div style="flex: 1.4" class="col-sm-4">
              <input required type="email" name="email" class="form-control" id="email">
            </div>
          </div>
          <!-- email  password Input > type :"password" -->
          <div class="d-flex align-items-center gap-2">
            <label for="password1" class="col-sm-2 col-form-label"> Password : </label>
            <div style="flex: 1.4" class="col-sm-4">
              <input required type="password" name="password1" class="form-control" id="password1">
            </div>
          </div>

          <!-- confirm email  password Input > type :"password" -->
          <div class="d-flex align-items-center gap-2">
            <label for="password2" class="col-sm-2 col-form-label"> Confirm Password : </label>
            <div style="flex: 1.4" class="col-sm-4">
              <input required type="password" name="password2" class="form-control" id="password2">
            </div>
          </div>
          <!-- {{registration_form}} -->
          <button style="width: fit-content;
          box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
          , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
          border: 2px solid black;" type="submit" class="btn btn-outline-dark mt-3"> submit</button>
        </form>

      </div>
      <div class="col-lg-6">
        <h1>Log in </h1>
        <br>
        <form action="{% url 'app1:login' %}" method="POST" class="d-flex flex-column gap-3 ">
          {% csrf_token %}
          <!-- email Input > type :type="email" -->
          <div class="d-flex align-items-center gap-2">
            <label for="inputEmail3" class="col-sm-2 col-form-label"> Email : </label>
            <div style="flex: 1.4" class="col-sm-4">
              <input required type="email" name="email" class="form-control" id="email">
            </div>
          </div>
          <!-- email  password Input > type :"password" -->
          <div class="d-flex align-items-center gap-2">
            <label for="password1" class="col-sm-2 col-form-label"> Password : </label>
            <div style="flex: 1.4" class="col-sm-4">
              <input required type="password" name="password1" class="form-control" id="password1">
            </div>
          </div>

          <!-- {{login_form}} -->
          <button style="width: fit-content;
            box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
            , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
            border: 2px solid black;" type="submit" class="btn btn-outline-dark btn-shadow mt-3"> submit</button>
        </form>
      </div>
    </div>
  </div>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
</body>

</html>